---
title: "Part 2 ENCODE"
output: html_notebook
---

### EXTRACTING SPECIFIC GENES FROM ENCODE (MOUSE) TPM File
1. Arguments introduced for the execution
```{r}
Prefix <- "~/projects/ER_proj/"
setwd(Prefix)
input1 <- "mm65.long.gene.with.expr.cshl.tsv" 
input2 <- "mouse_id_symbol_class.tsv"
```

2. Importing and manipulating the data
```{r}
#Load the library
library(dplyr)
library(stringr)



data<- read.delim(paste0(Prefix,"part2/", input1))
colnames(data)<- gsub("\\.","",colnames(data))#Remove ... and . from colnames introduced by R
#Removing other expression values from each cell (reformatting)
data2 <- as.data.frame(data[,1])
for (i in 2:ncol(data)) {
	data2[paste(colnames(data[i]))] <- str_split_fixed(data[,i],":",3)[,1]	
}
#data2$gene_id<-rownames(data) #add gene_ids from the data
#Leaving only TPM values
colnames(data2)[1] <- "gene_id"
```


```{r}
data3 <- data2 %>% dplyr::select(gene_id, everything()) #Place it in the first column
names(data3)[2] <- "symbol" #rename second column
write.table(data3,file="encode_TPM.tsv",quote=FALSE, sep="\t") #Exporting TPM values 
#Replace column names with proper tissue names
colnames(data3)<- gsub("LID20728LID20729Adrenaladult8wkscelllongPolyA","Adrenal",colnames(data3))
colnames(data3)<- gsub("LID20730LID20731Duodenumadult8wkscelllongPolyA","Duodenum",colnames(data3))
colnames(data3)<- gsub("LID20732LID20733Stomachadult8wkscelllongPolyA","Stomach",colnames(data3))
colnames(data3)<- gsub("LID20819LID20820SmIntestineadult8wkscelllongPolyA","Small_Intestine",colnames(data3))
colnames(data3)<- gsub("LID20821LID20822Ovaryadult8wkscelllongPolyA","Ovary",colnames(data3))
colnames(data3)<- gsub("LID20868LID20869Testisadult8wkscelllongPolyA","Testis",colnames(data3))
colnames(data3)<- gsub("LID20870LID20871Heartadult8wkscelllongPolyA","Heart",colnames(data3))
colnames(data3)<- gsub("LID20872LID20873Kidneyadult8wkscelllongPolyA","Kidney",colnames(data3))
colnames(data3)<- gsub("LID20920LID20921Lungadult8wkscelllongPolyA","Lung",colnames(data3))
colnames(data3)<- gsub("LID20922LID20923Thymusadult8wkscelllongPolyA","Thymus",colnames(data3))
colnames(data3)<- gsub("LID20924LID20925MammaryGlandadult8wkscelllongPolyA","Mammary",colnames(data3))
colnames(data3)<- gsub("LID21038LID21039Spleenadult8wkscelllongPolyA","Spleen",colnames(data3))
colnames(data3)<- gsub("LID21040LID21041Colonadult8wkscelllongPolyA","Colon",colnames(data3))
colnames(data3)<- gsub("LID21042LID21043Liveradult8wkscelllongPolyA","Liver",colnames(data3))
colnames(data3)<- gsub("LID21179LID21180GenitalFatPadadult8wkscelllongPolyA","Genital_Fat",colnames(data3))
colnames(data3)<- gsub("LID21181LID21182SubcFatPadadult8wkscelllongPolyA","Subc_Fat",colnames(data3))
colnames(data3)<- gsub("LID21183LID21184LgIntestineadult8wkscelllongPolyA","Large_Intestine",colnames(data3))
colnames(data3)<- gsub("LID46946LID46947CNSE115celllongPolyA","CNS_E11.5",colnames(data3))
colnames(data3)<- gsub("LID46948LID46949CNSE14celllongPolyA","CNS_E14",colnames(data3))
colnames(data3)<- gsub("LID46950LID46951CNSE18celllongPolyA","CNS_E18",colnames(data3))
colnames(data3)<- gsub("LID46983LID46984Placentaadult8wkscelllongPolyA","Placenta",colnames(data3))
colnames(data3)<- gsub("LID46985LID46986LimbE145celllongPolyA","Limb_E14.5",colnames(data3))
colnames(data3)<- gsub("LID46987LID46988WholeBrainE145celllongPolyA","Whole_Brain_E14.5",colnames(data3))
colnames(data3)<- gsub("LID47030LID47031Bladderadult8wkscelllongPolyA","Bladder",colnames(data3))
colnames(data3)<- gsub("LID47032LID47033Cortexadult8wkscelllongPolyA","Brain_COR",colnames(data3))
colnames(data3)<- gsub("LID47036LID47037Cerebellumadult8wkscelllongPolyA","Cerebellum",colnames(data3))
colnames(data3)<- gsub("LID47081LID47082FrontalLobeadult8wkscelllongPolyA","Brain_FRO",colnames(data3))
colnames(data3)<- gsub("LID47144LID47145LiverE14celllongPolyA","Liver_E14",colnames(data3))
colnames(data3)<- gsub("LID47146LID47147LiverE145celllongPolyA","Liver_E14.5",colnames(data3))
colnames(data3)<- gsub("LID47148LID47149LiverE18celllongPolyA","Liver_E18",colnames(data3))
colnames(data3)<- gsub("SID38132SID38133CH12adult8wkscelllongPolyA","CH12",colnames(data3))
colnames(data3)<- gsub("SID38134SID38135Liveradult8wkscelltotal","Liver_total",colnames(data3))

write.table(data3,file="encode_TPM_renamed.tsv",quote=FALSE, sep="\t") #Exporting Encode table with Renamed tissue names

```

3. Importing the gene list and joining them with the initial input
```{r}
ensembl <- read.table(paste0(Prefix,"part2/", input2), sep="\t",header=TRUE)#import the ensembl file that contains ENSEMBL ID and matching GeneNames
joined<- plyr::join(data3, ensembl, by="gene_id") #use join function to add a column of gene names/Class corresponding to the ENSEMBL ID to the last column
joined2<- na.omit(joined, cols="Class") #Remove the rows that contain non-matching genes
#joined2 is tha expression file for ERs
replaced <- joined2 %>% dplyr::select(Class, everything()) #place the last column to first column
replaced2 <- replaced %>% dplyr::select(Symbol, everything())#place the last column to first column
replaced3<-replaced2[order(replaced2$Class),] #Sort by Class

#Removing the embryo samples, ch12, and total RNA seq liver
replaced3[,"Liver_total"]<-NULL  
replaced3[,"CH12"]<-NULL #
replaced3[,"Liver_E18"]<-NULL 
replaced3[,"Liver_E14.5"]<-NULL 
replaced3[,"Liver_E14"]<-NULL 
replaced3[,"Whole_Brain_E14.5"]<-NULL 
replaced3[,"Limb_E14.5"]<-NULL 
replaced3[,"CNS_E18"]<-NULL 
replaced3[,"CNS_E14"]<-NULL 
replaced3[,"CNS_E11.5"]<-NULL 

write.table(replaced3,file="RMLP.encode.TPM.tsv",quote=FALSE, sep="\t",row.names=FALSE)

#Take mean of tireplaced4<- ssues with multiple sections (Brain, Cerebellum etc.)
replaced4 <- data.frame(sapply(replaced3[,5:ncol(replaced3)], function(x) as.numeric(as.character(x))))
replaced5<- cbind(replaced3[,1:4],replaced4)
replaced5$Brain <- rowMeans(replaced5[,grep("^Brain_",colnames(replaced5))],na.rm = TRUE) #Mean of the columns that have matching name
replaced5[,grep("^Brain_",colnames(replaced5))]<- NULL #remove those columns after adding mean column
#Order the columns by alphabetical order again
replaced6<-replaced5[,5:dim(replaced5)[2]]#Cut the matrix before ordering it by columns (to avoid gene_id and Description columns)
replaced7<-replaced6[ , order(names(replaced6))] #Order the columns by column names
final<-cbind(replaced3[1:4], replaced7) #Add first four columns back to the matrix
final$symbol<-NULL
write.table(final,file="RMLP.encode.TPM.brainav.tsv",quote=FALSE, sep="\t",row.names=FALSE)
```


### Tissue-wide expression plots using GTEx values

1. Arguments introduced for the execution
```{r}
input1 <- "RMLP.encode.TPM.brainav.tsv"
```

2. Importing and manipulating the data
```{r}
library(MASS)
library(ggplot2)
library(ggrepel)
library(ComplexHeatmap)
library(circlize)
library(ggplot2)
library(grid)
library(gridExtra)



##Tissue Wide Expression Plots for encode
data<- read.delim(input1)#"RMLP.encode.TPM.brainav.tsv"
scatter<- reshape2::melt(data, c("Symbol","Class","gene_id")) #data for scatterplot
colnames(scatter)<- c("Symbol","Class","gene_id","Tissue", "value") #change column names
scatter$value<- log(scatter$value+1)#Take log of the file (with a pseudocount)
```

3. SCATTER PLOTS
```{r}
#Calculate THRESHOLD for the specificity
genemean<- aggregate(scatter[, 5], list(scatter$Symbol), mean) #Row mean grouped by Gene
colnames(genemean)<- c("Symbol", "genemean") 
scatter2<- plyr::join(scatter, genemean, by="Symbol") #Add Rowmeans to the original data
scatter2$abs<- scatter2$value- scatter2$genemean #absolute distance of gene's expresion in tissue A from mean expression of this gene ins all tissues
res_vec <- vector() #res_vec file is a vector file that will contain all the residuals (tissue.vs.all) for all of the genes in all tissues
for (tissue in unique(scatter2$Tissue)){ #for every single tissue
	subset <- scatter2[with(scatter2, scatter2$Tissue %in% tissue),] #extract the data for a specific tissue
	res<- rlm(subset$value ~0 + subset$genemean) #linear model for that tissue 
	res_vec= c(res$residuals,res_vec)#this contains residuals for every gene in every tissuevsall combination
}
threshold <- 2.5*sd(res_vec) #The threshold is 2.5 times the standard deviation of all the residuals


##Seperate plots and calculations for each tissue
specific_genes<-vector() 
for (tissue in unique(scatter2$Tissue)){ #for each tissue
subset <- scatter2[with(scatter2, scatter2$Tissue %in% tissue),] #extract the data for a specific tissue
res<- rlm(subset$value ~0 + subset$genemean)#linear model for that tissue 
subset$res<- res$residuals #add residual values to the matrix
subset$diff<- abs(subset$res)-threshold #difference between gene's residual and threshold
spec<-subset(subset, diff>0 & abs>0) #extract specific genes in each tissue
specific_genes<- rbind(spec,specific_genes) #add these genes to the initial data
pdf(file=paste("mouse_results/",tissue,"specificityplot.pdf",sep="."),height=5,width=5)
print(ggplot(subset, aes(x=genemean, y=value,label=Symbol)) + 
	  scale_x_continuous(limits= c(0,5))+
	  scale_y_continuous(limits= c(0,5))+
	  geom_point(data=subset, col="black",size=0.5)+ #All data points will be black
	  geom_point(data=subset(subset, diff>0 & abs>0),col="red",size=2)+ #Except the specific genes
	  geom_text_repel(data=subset(subset, diff>0 & abs>0),segment.size  = 0.4,segment.color = "grey50",)+ #Add text to the specific genes
	  geom_smooth(method=rlm, formula = y ~0 + x, size=0.5,fullrange=TRUE)+ #abline will be from rlm function that passes through 0,0
	  xlab("mRNA mean abundance All Human Tissues")+
	  ylab(paste("mRNA mean abundance",tissue,sep=" "))+
	  theme(panel.background = element_blank(),
         panel.border=element_rect(fill=NA),
         panel.grid.major = element_blank(),
         panel.grid.minor = element_blank(),
         strip.background=element_blank(),
         axis.text.x=element_text(colour="black"),
         axis.text.y=element_text(colour="black"),
         axis.ticks=element_line(colour="black"),
        plot.margin=unit(c(1,1,1,1),"line")))
dev.off()
}
write.table(specific_genes, file="specific_genes_encode.tsv",quote=FALSE, row.names=FALSE,sep="\t")


```

4. HEATMAP
```{r}
rownames(data)<- data[,1] #assign gene names as rownames  
data2<- data[,-c(1:3)] #remove the first three columns for the heatmap
data3<- log(data2+1)#Take log of the file (with a pseudocount)
data4 <- t(scale(t(data3)))#Normalize by row (by gene)

pdf("mouse_results/heatmap.encode.logzscaled.pdf",height=12,width=8)
Heatmap(data4, name = "z-scale log(TPM)", 
	#col = colorRamp2(c(-3,0,4), c("cadetblue3","floralwhite", "maroon4"),space = "RGB"), 
    #cluster_rows = TRUE, 
    col = colorRamp2(c(-3,-1.5,0,1.5,3), c("#2c7bb6","#abd9e9","floralwhite","#fdae61", "#d7191c"),space = "RGB"),
    cluster_columns = TRUE,
    column_title = "mRNA Expression of Human Tissues (encode)", 
    column_title_gp = gpar(fontsize = 10, fontface = "bold"),
    column_names_gp = gpar(fontsize = 7, fontface = "bold"),
    row_title = "ER genes", row_title_rot = 90,
    row_title_gp = gpar(fontsize = 8, fontface = "bold"),
    cluster_rows = TRUE,
    show_row_names = TRUE,
    row_names_gp = gpar(fontsize = 5), #row names size
    #column_order = 1:dim(data4)[2],#Keep the column order, make clustering FALSE for this
    row_dend_side = "right", #Dendogram on the right side
    #row_order = 1:dim(data4)[1], #Keep the row order, make clustering FALSE for this
    show_column_dend = TRUE, #
    column_dend_side = "top",
    column_names_side = "bottom",
    split = data$Class, #Splitting by Class
    gap = unit(1, "mm"), #Gap
    )
dev.off()

```

5. PCA
```{r}
##PCA Plotting 
data_pca<-prcomp(data4,center=TRUE) #PCA 
data_out <- as.data.frame(data_pca$x) #X table of PCA
data_out$Class<- data$Class
data_out$Symbol<- rownames(data)
data_out$Class <- factor(data_out$Class , levels = unique(data_out$Class))#keep the order of species
##Calculation for percentage of variance explained by each component
eigs <- data_pca$sdev^2#Calculate percentage for PC values
percentage<- round(eigs/sum(eigs)*100,2)#Calculate percentage for PC values
percentage <- paste( colnames(data_out), "(", paste( as.character(percentage), "%", ")", sep="") ) #Calculate percentage for PC values

## PLOT FOR X ALL LABELS
pdf("mouse_results/pca_encode.all.labels.pdf",height=5,width=7)
print(ggplot(data_out,aes(x=PC1,y=PC2,color=Class,label=Symbol))+
	scale_color_manual(values = c("darkgreen","grey","darkred","darkblue","pink","green1","red","steelblue1","purple","tan"))+
	geom_hline(yintercept = 0, lty = 2) +
	geom_vline(xintercept = 0, lty = 2)+
	geom_point(alpha = 0.8, size = 1.2)+
	geom_text(aes(label=Symbol),hjust=0, vjust=-1)+
	theme(panel.background = element_blank(),
		panel.border=element_rect(fill=NA),
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		strip.background=element_blank(),
		axis.text.x=element_text(colour="black"),
		axis.text.y=element_text(colour="black"),
		axis.ticks=element_line(colour="black"),
		plot.margin=unit(c(1,1,1,1),"line"))+
	xlab(percentage[1]) + ylab(percentage[2]) #Labels containing percentages
	)
dev.off()

```

```{r}
## PLOT FOR X SOME LABELS
pdf("mouse_results/pca_encode.pdf",height=5,width=7)
print(ggplot(data_out,aes(x=PC1,y=PC2,color=Class,label=Symbol))+
	scale_color_manual(values = c("darkgreen","grey","darkred","darkblue","pink","green1","red","steelblue1","purple","tan"))+
	geom_hline(yintercept = 0, lty = 2) +
	geom_vline(xintercept = 0, lty = 2)+
	geom_point(alpha = 0.8, size = 1.2)+
	geom_text(data=subset(data_out, PC1 < -3.5|PC1 > 3.5| PC2 > 3.5 | PC2 < -3),
		aes(label=Symbol),hjust=0, vjust=-1)+
	theme(panel.background = element_blank(),
		panel.border=element_rect(fill=NA),
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		strip.background=element_blank(),
		axis.text.x=element_text(colour="black"),
		axis.text.y=element_text(colour="black"),
		axis.ticks=element_line(colour="black"),
		plot.margin=unit(c(1,1,1,1),"line"))+
	xlab(percentage[1]) + ylab(percentage[2]) #Labels containing percentages
	)
dev.off()



##PLOT FOR LOADINGS ALL LABELS
data_out_r <- as.data.frame(data_pca$rotation) #rotation data (loadings)
data_out_r$Symbol <- row.names(data_out_r) 
pdf(file="mouse_results/pca_encode.loadings.all.labels.pdf",height=5,width=5)
print(ggplot(data_out_r,aes(x=PC1,y=PC2,label=Symbol))+
	geom_point()+
	geom_hline(yintercept = 0, lty = 2) +
	geom_vline(xintercept = 0, lty = 2)+
	geom_point(alpha = 0.8, size = 2)+
	geom_text(aes(label=Symbol),hjust=0, vjust=-1)+
	theme(panel.background = element_blank(),
		panel.border=element_rect(fill=NA),
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		strip.background=element_blank(),
		axis.text.x=element_text(colour="black"),
		axis.text.y=element_text(colour="black"),
		axis.ticks=element_line(colour="black"),
		plot.margin=unit(c(1,1,1,1),"line"))+
	xlab(percentage[1]) + ylab(percentage[2])
	)
dev.off()



##PLOT FOR LOADINGS SOME LABELS
data_out_r <- as.data.frame(data_pca$rotation) #rotation data (loadings)
data_out_r$Symbol <- row.names(data_out_r) 
pdf(file="mouse_results/pca_encode.loadings.some.labels.pdf",height=5,width=5)
print(ggplot(data_out_r,aes(x=PC1,y=PC2,label=Symbol))+
	geom_point()+
	geom_hline(yintercept = 0, lty = 2) +
	geom_vline(xintercept = 0, lty = 2)+
	geom_point(alpha = 0.8, size = 2)+
	geom_text(data=subset(data_out_r, PC1 > 0.2),
	aes(label=Symbol),hjust=0, vjust=-1)+
	theme(panel.background = element_blank(),
		panel.border=element_rect(fill=NA),
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		strip.background=element_blank(),
		axis.text.x=element_text(colour="black"),
		axis.text.y=element_text(colour="black"),
		axis.ticks=element_line(colour="black"),
		plot.margin=unit(c(1,1,1,1),"line"))+
	xlab(percentage[1]) + ylab(percentage[2])
	)
dev.off()

```

